title: Opus-Codium People
description: An interactive map of our experts.
github_project: opus-codium/map
baseurl: "" # the subpath of your site, e.g. /map
url: "https://opus-codium.github.io/map" # the base hostname & protocol for your site, e.g. https://example.com
thunderforest_apikey: "f001bec5e17447b0b597e5a8e766bbf2" # the Thunderforest API key for map tiles

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
